{
 "title": "clickhouse",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(up{job='clickhouse'},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "状态",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"clickhouse\",instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ZooKeeper 中保存的临时节点数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ClickHouseMetrics_EphemeralNode{job=\"clickhouse\",instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ZK 事件订阅数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ClickHouseMetrics_ZooKeeperWatch{instance=\"$instance\", job=\"clickhouse\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "被抑制的 Insert 查询数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ClickHouseMetrics_DelayedInserts {job=\"clickhouse\",instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "pending 的异步插入到分布式表的文件数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ClickHouseMetrics_DistributedSend {job=\"clickhouse\",instance=~ \"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "已打开的文件数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ClickHouseProfileEvents_FileOpen    {instance=\"$instance\", job=\"clickhouse\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "全局线程池中的线程数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ClickHouseMetrics_GlobalThread {instance=\"$instance\", job=\"clickhouse\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "全局线程池中的线程数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ClickHouseMetrics_GlobalThread {instance=\"$instance\", job=\"clickhouse\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "本地线程池中的线程数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ClickHouseMetrics_LocalThread  {instance=\"$instance\", job=\"clickhouse\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "本地线程池中活跃的线程数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ClickHouseMetrics_LocalThreadActive   {instance=\"$instance\", job=\"clickhouse\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "当前执行的查询中所分配的内存总量",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ClickHouseMetrics_MemoryTracking   {instance=\"$instance\", job=\"clickhouse\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "事件", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "被插入到所有表中的行数",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(ClickHouseProfileEvents_InsertedRows {job=\"clickhouse\",instance=~ \"$instance\"}[$__interval])",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  {
   "title": "被插入到所有表中的字节数",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "increase(ClickHouseProfileEvents_InsertedBytes  {job=\"clickhouse\",instance=~ \"$instance\"}[$__interval])",
     "legendFormat": "{{gc}}"
    }
   ]
  }
 ]
}