{
 "title": "cluster",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "nodeexporter",
    "label": "nodeexporter",
    "query": {
     "query": "label_values(node_uname_info, job)"
    }
   },
   {
    "name": "name",
    "label": "name",
    "query": {
     "query": "label_values(node_exporter_build_info{env=~'$env'},name)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(node_exporter_build_info{name=~'$name'},instance)"
    }
   },
   {
    "name": "namenode",
    "query": {
     "query": "label_values(process_start_time_seconds{job='namenode'},instance)"
    }
   },
   {
    "name": "resourcemanager",
    "label": "resourcemanager",
    "query": {
     "query": "label_values(process_start_time_seconds{job='resourcemanager'},instance)"
    }
   },
   {
    "name": "datanode",
    "query": {
     "query": "label_values(process_start_time_seconds{job='datanode'},instance)"
    }
   },
   {
    "name": "nodemanager",
    "label": "nodemanager",
    "query": {
     "query": "label_values(process_start_time_seconds{job='nodemanager'},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "总览",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(1 - avg(irate(node_cpu_seconds_total{job=~\"$nodeexporter\",mode=\"idle\",instance=~\"$instance\"}[5m])) by (instance)) * 100",
     "legendFormat": "cpu使用率"
    },
    {
     "expr": "(sum(node_memory_MemTotal_bytes{job=~\"$nodeexporter\",instance=~\"$instance\"} - node_memory_MemAvailable_bytes{job=~\"$nodeexporter\",instance=~\"$instance\"}) / sum(node_memory_MemTotal_bytes{job=~\"$nodeexporter\",instance=~\"$instance\"}))*100",
     "legendFormat": "内存使用率"
    },
    {
     "expr": "(sum(avg(node_filesystem_size_bytes{job=~\"$nodeexporter\",instance=~\"$instance\",fstype=~\"xfs|ext.*\"})by(device,instance)) - sum(avg(node_filesystem_free_bytes{job=~\"$nodeexporter\",instance=~\"$instance\",fstype=~\"xfs|ext.*\"})by(device,instance))) *100/(sum(avg(node_filesystem_avail_bytes{job=~\"$nodeexporter\",instance=~\"$instance\",fstype=~\"xfs|ext.*\"})by(device,instance))+(sum(avg(node_filesystem_size_bytes{job=~\"$nodeexporter\",instance=~\"$instance\",fstype=~\"xfs|ext.*\"})by(device,instance)) - sum(avg(node_filesystem_free_bytes{job=~\"$nodeexporter\",instance=~\"$instance\",fstype=~\"xfs|ext.*\"})by(device,instance))))",
     "legendFormat": "磁盘使用率"
    }
   ]
  },
  {
   "title": "机器总数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{job=\"nodeexporter\",instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "总核数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{job=~\"$nodeexporter\", mode='system',instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "总内存",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{job=~\"$nodeexporter\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "已用内存",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{job=~\"$nodeexporter\",instance=~\"$instance\"} - node_memory_MemAvailable_bytes{job=~\"$nodeexporter\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "总磁盘容量",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(avg(node_filesystem_size_bytes{job=~\"$nodeexporter\",fstype=~\"xfs|ext.*\",instance=~\"$instance\"})by(device,instance))"
    }
   ]
  },
  {
   "title": "已用磁盘容量",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(avg(node_filesystem_size_bytes{job=~\"$nodeexporter\",fstype=~\"xfs|ext.*\",instance=~\"$instance\"})by(device,instance)) - sum(avg(node_filesystem_free_bytes{job=~\"$nodeexporter\",fstype=~\"xfs|ext.*\",instance=~\"$instance\"})by(device,instance)) "
    }
   ]
  },
  {
   "title": "HDFS总量",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(Hadoop_DataNode_Capacity{name=\"FSDatasetState\",instance=~\"$datanode\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HDFS已用量",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(Hadoop_DataNode_DfsUsed{name=\"FSDatasetState\",instance=~\"$datanode\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HDFS文件总数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(Hadoop_NameNode_TotalFileOps{name=\"NameNodeActivity\",job=\"namenode\",instance=~\"$namenode\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Yarn虚拟内存",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(Hadoop_NodeManager_AllocatedGB{instance=~\"$nodemanager\"}+Hadoop_NodeManager_AvailableGB{instance=~\"$nodemanager\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "总虚拟核数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(Hadoop_NodeManager_AvailableVCores{instance=~\"$nodemanager\"}+Hadoop_NodeManager_AllocatedVCores{instance=~\"$nodemanager\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "在线DataNode",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(up{instance=~\"$datanode\"} == 1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "集群1|5|15分钟负载情况",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(node_load1 {job=\"$nodeexporter\",instance=~\"$instance\"})",
     "legendFormat": "一分钟负载"
    },
    {
     "expr": "avg(node_load5 {job=\"$nodeexporter\",instance=~\"$instance\"})",
     "legendFormat": "五分钟负载"
    },
    {
     "expr": "avg(node_load15 {job=\"$nodeexporter\",instance=~\"$instance\"})",
     "legendFormat": "十五分钟负载"
    }
   ]
  },
  {
   "title": "集群流量图",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (ip) (rate(node_network_receive_bytes_total{instance=~\"$instance\", device != \"lo\"}[5m]))",
     "legendFormat": "接收流量"
    },
    {
     "expr": "sum by (ip) (rate(node_network_transmit_bytes_total{instance=~\"$instance\", device != \"lo\"}[5m]))",
     "legendFormat": "发送流量"
    }
   ]
  },
  {
   "title": "集群总内存与集群平均内存使用率",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{job=~\"$nodeexporter\",instance=~\"$instance\"})",
     "legendFormat": "总内存"
    },
    {
     "expr": "sum(node_memory_MemTotal_bytes{job=~\"$nodeexporter\",instance=~\"$instance\"} - node_memory_MemAvailable_bytes{job=~\"$nodeexporter\",instance=~\"$instance\"})",
     "legendFormat": "总已用"
    },
    {
     "expr": "(sum(node_memory_MemTotal_bytes{job=~\"$nodeexporter\",instance=~\"$instance\"} - node_memory_MemAvailable_bytes{job=~\"$nodeexporter\",instance=~\"$instance\"}) / sum(node_memory_MemTotal_bytes{job=~\"$nodeexporter\",instance=~\"$instance\"}))*100",
     "legendFormat": "总平均使用率"
    }
   ]
  },
  {
   "title": "集群总负载与集群平均CPU使用率",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{job=~\"$nodeexporter\", mode='system',instance=~\"$instance\"})",
     "legendFormat": "总核数"
    },
    {
     "expr": "sum(node_load5{job=~\"$job\"})",
     "legendFormat": "总5分钟负载"
    },
    {
     "expr": "avg(1 - avg(irate(node_cpu_seconds_total{job=~\"$nodeexporter\",mode=\"idle\",instance=~\"$instance\"}[5m])) by (instance)) * 100",
     "legendFormat": "总平均使用率"
    }
   ]
  },
  {
   "title": "集群总磁盘与集群平均磁盘使用率",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(avg(node_filesystem_size_bytes{job=~\"$nodeexporter\",fstype=~\"xfs|ext.*\",instance=~\"$instance\"})by(device,instance))",
     "legendFormat": "总磁盘量"
    },
    {
     "expr": "sum(avg(node_filesystem_size_bytes{job=~\"$nodeexporter\",instance=~\"$instance\",fstype=~\"xfs|ext.*\"})by(device,instance)) - sum(avg(node_filesystem_free_bytes{job=~\"$nodeexporter\",instance=~\"$instance\",fstype=~\"xfs|ext.*\"})by(device,instance))",
     "legendFormat": "总使用量"
    },
    {
     "expr": "(sum(avg(node_filesystem_size_bytes{job=~\"$nodeexporter\",instance=~\"$instance\",fstype=~\"xfs|ext.*\"})by(device,instance)) - sum(avg(node_filesystem_free_bytes{job=~\"$nodeexporter\",instance=~\"$instance\",fstype=~\"xfs|ext.*\"})by(device,instance))) *100/(sum(avg(node_filesystem_avail_bytes{job=~\"$nodeexporter\",instance=~\"$instance\",fstype=~\"xfs|ext.*\"})by(device,instance))+(sum(avg(node_filesystem_size_bytes{job=~\"$nodeexporter\",instance=~\"$instance\",fstype=~\"xfs|ext.*\"})by(device,instance)) - sum(avg(node_filesystem_free_bytes{job=~\"$nodeexporter\",instance=~\"$instance\",fstype=~\"xfs|ext.*\"})by(device,instance))))",
     "legendFormat": "总平均使用率"
    }
   ]
  },
  {
   "title": "内存使用率排名",
   "type": "table-old",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "node_uname_info{job=~\"$nodeexporter\",instance=~\"$instance\"} - 0",
     "legendFormat": "主机名"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{job=~\"$nodeexporter\",instance=~\"$instance\"} / (node_memory_MemTotal_bytes{job=~\"$nodeexporter\",instance=~\"$instance\"})))* 100",
     "legendFormat": "CPU使用率"
    }
   ]
  },
  {
   "title": "CPU使用率排名",
   "type": "table-old",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 32 },
   "targets": [
    {
     "expr": "node_uname_info{job=~\"$nodeexporter\",instance=~\"$instance\"} - 0",
     "legendFormat": "主机名"
    },
    {
     "expr": "(1 - avg(irate(node_cpu_seconds_total{job=~\"$nodeexporter\",instance=~\"$instance\",mode=\"idle\"}[5m])) by (instance)) * 100",
     "legendFormat": "CPU使用率"
    }
   ]
  },
  {
   "title": "磁盘使用率排名",
   "type": "table-old",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 32 },
   "targets": [
    {
     "expr": "node_uname_info{job=~\"$nodeexporter\",instance=~\"$instance\"} - 0",
     "legendFormat": "主机名"
    },
    {
     "expr": "1- (sum(node_filesystem_free_bytes{fstype=~\"ext4|xfs\",instance=~\"$instance\"}) by (instance) / sum(node_filesystem_size_bytes{fstype=~\"ext4|xfs\",instance=~\"$instance\"})by (instance))",
     "legendFormat": "磁盘使用率"
    }
   ]
  },
  {
   "title": "服务器资源总览表(每页10行)",
   "type": "table-old",
   "description": "分区使用率、磁盘读取、磁盘写入、下载带宽、上传带宽，如果有多个网卡或者多个分区，是采集的使用率最高的网卡或者分区的数值。",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "node_uname_info{job=~\"$nodeexporter\",instance=~\"$instance\"} - 0",
     "legendFormat": "主机名"
    },
    {
     "expr": "sum(time() - node_boot_time_seconds{job=~\"$nodeexporter\",instance=~\"$instance\"})by(instance)",
     "legendFormat": "运行时间"
    },
    {
     "expr": "node_memory_MemTotal_bytes{job=~\"$nodeexporter\",instance=~\"$instance\"} - 0",
     "legendFormat": "总内存"
    },
    {
     "expr": "count(node_cpu_seconds_total{job=~\"$nodeexporter\",mode='system',instance=~\"$instance\"}) by (instance)",
     "legendFormat": "总核数"
    },
    {
     "expr": "node_load5{job=~\"$nodeexporter\",instance=~\"$instance\"}",
     "legendFormat": "5分钟负载"
    },
    {
     "expr": "(1 - avg(irate(node_cpu_seconds_total{job=~\"$nodeexporter\",mode=\"idle\",instance=~\"$instance\"}[5m])) by (instance)) * 100",
     "legendFormat": "CPU使用率"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{job=~\"$nodeexporter\",instance=~\"$instance\"} / (node_memory_MemTotal_bytes{job=~\"$nodeexporter\",instance=~\"$instance\"})))* 100",
     "legendFormat": "内存使用率"
    },
    {
     "expr": "1- (sum(node_filesystem_free_bytes{fstype=~\"ext4|xfs\",instance=~\"$instance\"}) by (instance) / sum(node_filesystem_size_bytes{fstype=~\"ext4|xfs\",instance=~\"$instance\"})by (instance))",
     "legendFormat": "磁盘使用率"
    },
    {
     "expr": "max(irate(node_disk_read_bytes_total{job=~\"$nodeexporter\",instance=~\"$instance\"}[5m])) by (instance)",
     "legendFormat": "最大读取"
    },
    {
     "expr": "max(irate(node_disk_written_bytes_total{job=~\"$nodeexporter\",instance=~\"$instance\"}[5m])) by (instance)",
     "legendFormat": "最大写入"
    },
    {
     "expr": "max(irate(node_network_receive_bytes_total{job=~\"$nodeexporter\",instance=~\"$instance\"}[5m])*8) by (instance)",
     "legendFormat": "下载带宽"
    },
    {
     "expr": "max(irate(node_network_transmit_bytes_total{job=~\"$nodeexporter\",instance=~\"$instance\"}[5m])*8) by (instance)",
     "legendFormat": "上传带宽"
    }
   ]
  }
 ]
}