{
 "title": "ElasticSearch",
 "description": "ElasticSearch cluster stats.\r\n\r\nRevision 1 of this dashboard is the same as the Infinity Dashboard Revision 4 (https://grafana.com/dashboards/2322)\r\n\r\nThis is a cleaned up copy with all control characters removed from the dashboard file.  When downloading version 4 of the original Infinity elasticsearch dashboard via curl, the resulting file is corrupted with a missing final curly brace.\r\n",
 "tags": [
  "elasticsearch",
  "App"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(elasticsearch_indices_docs,cluster)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(elasticsearch_indices_docs{cluster=\"$cluster\", name!=\"\"},instance)"
    }
   },
   {
    "name": "host",
    "label": "host",
    "query": {
     "query": "label_values(elasticsearch_indices_docs{instance=\"$instance\",cluster=\"$cluster\", name!=\"\"},host)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "集群",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "集群健康",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_status{instance=~\"$instance\",cluster=\"$cluster\",color=\"red\"}==1 or (elasticsearch_cluster_health_status{instance=~\"$instance\",cluster=\"$cluster\",color=\"green\"}==1)+4 or (elasticsearch_cluster_health_status{instance=~\"$instance\",cluster=\"$cluster\",color=\"yellow\"}==1)+2"
    }
   ]
  },
  {
   "title": "节点数量",
   "type": "stat",
   "description": "Number of nodes in the cluster",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_number_of_nodes{instance=~\"$instance\",cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "数据节点",
   "type": "stat",
   "description": "Number of data nodes in the cluster",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_number_of_data_nodes{instance=~\"$instance\",cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "处理中任务",
   "type": "stat",
   "description": "Cluster level changes which have not yet been executed",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_number_of_pending_tasks{instance=~\"$instance\",cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "分片",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {}
   ]
  },
  {
   "title": "主分片",
   "type": "stat",
   "description": "The number of primary shards in your cluster. This is an aggregate total across all indices.",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 5 },
   "repeat": "shard_type",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_active_primary_shards{instance=~\"$instance\",cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "分片数量",
   "type": "stat",
   "description": "Aggregate total of all shards across all indices, which includes replica shards",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_active_shards{instance=~\"$instance\",cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "初始化分片",
   "type": "stat",
   "description": "Count of shards that are being freshly created",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_initializing_shards{instance=~\"$instance\",cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "重定向分片",
   "type": "stat",
   "description": "The number of shards that are currently moving from one node to another node.",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_relocating_shards{instance=~\"$instance\",cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "延迟分片",
   "type": "stat",
   "description": "Shards delayed to reduce reallocation overhead",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_delayed_unassigned_shards{instance=~\"$instance\",cluster=\"$cluster\"} "
    }
   ]
  },
  {
   "title": "未分配分片",
   "type": "stat",
   "description": "The number of shards that exist in the cluster state, but cannot be found in the cluster itself",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_unassigned_shards{instance=~\"$instance\",cluster=\"$cluster\"} "
    }
   ]
  },
  {
   "title": "JVM GC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {}
   ]
  },
  {
   "title": "GC 次数",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "GCs" }
   ],
   "targets": [
    {
     "expr": "irate(elasticsearch_jvm_gc_collection_seconds_count{instance=~\"$instance\",cluster=\"$cluster\",host=~\"$host\"}[$interval])",
     "legendFormat": "{{name}} - {{gc}}"
    }
   ]
  },
  {
   "title": "GC 时间",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "s", "label": "Time" }
   ],
   "targets": [
    {
     "expr": "irate(elasticsearch_jvm_gc_collection_seconds_sum{instance=~\"$instance\",cluster=\"$cluster\",host=~\"$host\"}[$interval])",
     "legendFormat": "{{name}} - {{gc}}"
    }
   ]
  },
  {
   "title": "事务日志",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {}
   ]
  },
  {
   "title": "刷新总次数",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(elasticsearch_indices_translog_operations{instance=~\"$instance\",cluster=\"$cluster\",host=~\"$host\"}[$interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "日志总大小",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_indices_translog_size_in_bytes{instance=~\"$instance\",cluster=\"$cluster\",host=~\"$host\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "CPU and Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {}
   ]
  },
  {
   "title": "负载平均值",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short", "label": "CPU usage" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_os_load1{instance=~\"$instance\",cluster=\"$cluster\",host=~\"$host\"}",
     "legendFormat": "load1: {{name}}"
    },
    {
     "expr": "elasticsearch_os_load5{instance=~\"$instance\",cluster=\"$cluster\",host=~\"$host\"}",
     "legendFormat": "load5: {{name}}"
    },
    {
     "expr": "elasticsearch_os_load15{instance=~\"$instance\",cluster=\"$cluster\",host=~\"$host\"}",
     "legendFormat": "load15: {{name}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "description": "CPU在某个时间段内正在执行或等待执行的指令的百分比",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "percent", "label": "CPU usage" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_process_cpu_percent{instance=~\"$instance\",cluster=\"$cluster\",host=~\"$host\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "JVM memory usage",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "bytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_jvm_memory_used_bytes{instance=~\"$instance\",cluster=\"$cluster\",host=~\"$host\"}",
     "legendFormat": "{{name}} used: {{area}}"
    },
    {
     "expr": "elasticsearch_jvm_memory_max_bytes{instance=~\"$instance\",cluster=\"$cluster\",host=~\"$host\"}",
     "legendFormat": "{{name}} max: {{area}}"
    },
    {
     "expr": "elasticsearch_jvm_memory_pool_peak_used_bytes{instance=~\"$instance\",cluster=\"$cluster\",host=~\"$host\"}",
     "legendFormat": "{{name}} peak used pool: {{pool}}"
    }
   ]
  },
  {
   "title": "JVM memory committed",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "bytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_jvm_memory_committed_bytes{instance=~\"$instance\",cluster=\"$cluster\",host=~\"$host\"}",
     "legendFormat": "{{name}} committed: {{area}}"
    },
    {
     "expr": "elasticsearch_jvm_memory_max_bytes{instance=~\"$instance\",cluster=\"$cluster\",host=~\"$host\"}",
     "legendFormat": "{{name}} max: {{area}}"
    }
   ]
  },
  {
   "title": "文档",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "targets": [
    {}
   ]
  },
  {
   "title": "节点文档数量",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_indices_docs{instance=~\"$instance\",cluster=\"$cluster\",host=~\"$host\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "文档索引速率",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 52 },
   "yaxes": [
    { "format": "short", "label": "index calls/s" }
   ],
   "targets": [
    {
     "expr": "irate(elasticsearch_indices_indexing_index_total{instance=~\"$instance\",cluster=\"$cluster\",host=~\"$host\"}[$interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "文档删除速度",
   "type": "graph",
   "description": "Count of deleted documents on this node",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "short", "label": "Documents/s" }
   ],
   "targets": [
    {
     "expr": "irate(elasticsearch_indices_docs_deleted{instance=~\"$instance\",cluster=\"$cluster\",host=~\"$host\"}[$interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "文档合并速度",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 63 },
   "yaxes": [
    { "format": "short", "label": "Documents/s" }
   ],
   "targets": [
    {
     "expr": "rate(elasticsearch_indices_merges_docs_total{instance=~\"$instance\",cluster=\"$cluster\",host=~\"$host\"}[$interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "文档合并字节",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 63 },
   "yaxes": [
    { "format": "decbytes", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "irate(elasticsearch_indices_merges_total_size_bytes_total{instance=~\"$instance\",cluster=\"$cluster\",host=~\"$host\"}[$interval])",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}