{
 "title": "Hadoop DN Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(process_start_time_seconds{job=\"datanode\"}, instance)"
    }
   },
   { "name": "namespace", "label": "Namespace", "query": "datanode" },
   { "name": "interval", "label": "时间间隔", "query": "30s,1m,2m,3m,5m,10m,30m" }
  ]
 },
 "panels": [
  { "title": "集群信息", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "DN节点",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "process_start_time_seconds{job=\"datanode\",instance=~\"$instance\"}"
    },
    {
     "expr": "Hadoop_DataNode_DfsUsed{job=\"datanode\", name=\"FSDatasetState\",instance=~\"$instance\"}/1024/1024/1024"
    },
    {
     "expr": "Hadoop_DataNode_Capacity{job=\"datanode\", name=\"FSDatasetState\",instance=~\"$instance\"}/1024/1024/1024"
    }
   ]
  },
  {
   "title": "Hdfs平均写入时间",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "Hadoop_DataNode_WriteBlockOpAvgTime{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "内存使用率",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(jvm_memory_pool_bytes_used{instance=~\"$instance\"}) by (instance) / (sum(jvm_memory_pool_bytes_max{instance=~\"$instance\"}) by (instance)))* 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU使用率",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rate(process_cpu_seconds_total{instance=~\"$instance\"}[$interval])) by (instance) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "HDFS空间使用率",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(Hadoop_DataNode_DfsUsed{instance=~\"$instance\"}) by (instance) / (sum(Hadoop_DataNode_Capacity{instance=~\"$instance\"}) by (instance)))* 100"
    }
   ]
  },
  { "title": "JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "GC次数",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(Hadoop_DataNode_GcCount{instance=~\"$instance\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "GC时间",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(Hadoop_DataNode_GcTimeMillis{instance=~\"$instance\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "堆使用情况",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "Hadoop_DataNode_MemHeapUsedM{instance=~\"$instance\"}",
     "legendFormat": "{{instance}} used"
    },
    {
     "expr": "Hadoop_DataNode_MemHeapMaxM{instance=~\"$instance\"}",
     "legendFormat": "{{instance}} max"
    }
   ]
  }
 ]
}