{
 "title": "Hadoop NN Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(process_start_time_seconds{job=\"namenode\"}, instance)"
    }
   },
   { "name": "namespace", "label": "Namespace", "query": "namenode" },
   { "name": "interval", "label": "时间间隔", "query": "30s,1m,2m,3m,5m,10m,30m" }
  ]
 },
 "panels": [
  {
   "title": "内存使用率",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(jvm_memory_pool_bytes_used{instance=~\"$instance\"}) by (instance) / (sum(jvm_memory_pool_bytes_max{instance=~\"$instance\"}) by (instance)))* 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU使用率",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rate(process_cpu_seconds_total{instance=~\"$instance\"}[$interval])) by (instance) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "块总数\t",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Hadoop_NameNode_BlocksTotal{instance=~\"$instance\",name=\"FSNamesystem\"}"
    }
   ]
  },
  {
   "title": "损坏块总数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 9, "y": 0 },
   "targets": [
    {
     "expr": "Hadoop_NameNode_CorruptBlocks{instance=~\"$instance\",name=\"FSNamesystem\"}\t"
    }
   ]
  },
  { "title": "集群信息", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "丢失块总数\t",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "Hadoop_NameNode_MissingBlocks{instance=~\"$instance\",name=\"FSNamesystem\"}\t"
    }
   ]
  },
  {
   "title": "未复制块数量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "Hadoop_NameNode_UnderReplicatedBlocks{instance=~\"$instance\",name=\"FSNamesystem\"}\t"
    }
   ]
  },
  {
   "title": "磁盘容量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "Hadoop_NameNode_CapacityTotal{instance=~\"$instance\",name=\"FSNamesystem\"}/1024/1024/1024",
     "legendFormat": "磁盘总容量"
    },
    {
     "expr": "Hadoop_NameNode_CapacityUsed{instance=\"test-hadoop001:9222\",job=\"hadoop-nn\",name=\"FSNamesystem\"}/1024/1024/1024",
     "legendFormat": "dfs使用量"
    },
    {
     "expr": "Hadoop_NameNode_CapacityUsed{instance=\"test-hadoop001:9222\",job=\"hadoop-nn\",name=\"FSNamesystem\"}/1024/1024/1024",
     "legendFormat": "dfs剩余量"
    },
    {
     "expr": "Hadoop_NameNode_CapacityUsedNonDFS{instance=\"test-hadoop001:9222\",job=\"hadoop-nn\",name=\"FSNamesystem\"}/1024/1024/1024",
     "legendFormat": "非dfs使用量"
    }
   ]
  },
  { "title": "JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "GC次数",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(Hadoop_NameNode_GcCount{instance=~\"$instance\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "GC时间",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(Hadoop_NameNode_GcTimeMillis{instance=~\"$instance\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "年轻代GC累计次数",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "jvm_gc_collection_seconds_count{gc=\"PS Scavenge\",instance=~\"$instance\",job=\"namenode\"}",
     "legendFormat": "test-hadoop001"
    }
   ]
  },
  {
   "title": "老年代GC累计次数",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "jvm_gc_collection_seconds_count{gc=\"PS MarkSweep\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "年轻代GC累计时间",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "jvm_gc_collection_seconds_sum{gc=\"PS Scavenge\", instance=~\"$instance\", job=\"namenode\"}",
     "legendFormat": "test-hadoop001"
    }
   ]
  },
  {
   "title": "老年代GC累计时间",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "jvm_gc_collection_seconds_sum{gc=\"PS MarkSweep\", instance=~\"$instance\", job=\"namenode\"}",
     "legendFormat": "test-hadoop001"
    }
   ]
  },
  {
   "title": "堆使用情况",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "Hadoop_NameNode_MemHeapUsedM{instance=~\"$instance\"}",
     "legendFormat": "{{instance}} used"
    },
    {
     "expr": "Hadoop_NameNode_MemHeapMaxM{instance=~\"$instance\"}",
     "legendFormat": "{{instance}} max"
    }
   ]
  }
 ]
}