{
 "title": "HBase",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "HRegionServer",
    "label": "HRegionServer",
    "query": {
     "query": "label_values(process_start_time_seconds{job=\"HRegionServer\"},instance)"
    }
   },
   {
    "name": "HMaster",
    "query": {
     "query": "label_values(process_start_time_seconds{job=\"HMaster\"},instance)"
    }
   },
   {
    "name": "RESTServer",
    "label": "RESTServer",
    "query": {
     "query": "label_values(up{job='RESTServer'},instance)"
    }
   },
   {
    "name": "ThriftServer",
    "label": "ThriftServer",
    "query": {
     "query": "label_values(up{job='ThriftServer'},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "HMaster堆内存使用率",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(hadoop_hbase_memheapusedm{job=\"HMaster\",instance=~\"$HMaster\"}/hadoop_hbase_memheapmaxm{job=\"HMaster\",instance=~\"$HMaster\"})*100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "在线Master数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{instance=~\"$HMaster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "在线RegionServer数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hadoop_hbase_numregionservers{instance=~\"$HMaster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "在线RESTServer数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{instance=~\"$RESTServer\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "在线ThriftServer数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{instance=~\"$ThriftServer\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "离线RegionServer数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hadoop_hbase_numdeadregionservers{instance=~\"$HMaster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Region 个数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(hadoop_hbase_regioncount{instance=~\"$HRegionServer\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Store 个数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(hadoop_hbase_storecount{instance=~\"$HRegionServer\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Storefile 个数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(hadoop_hbase_storefilecount{instance=~\"$HRegionServer\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Storefile 大小",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(hadoop_hbase_storefilesize{instance=~\"$HRegionServer\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Assign成功次数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hadoop_hbase_assignsubmittedcount{instance=~\"$HMaster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "平衡次数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hadoop_hbase_balancercluster_num_ops{instance=~\"$HMaster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Region分裂次数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hadoop_hbase_splittime_num_ops{instance=~\"$HMaster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Get 请求时间超过1s的数量",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(hadoop_hbase_slowgetcount{instance=~\"$HRegionServer\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "图表", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "HMaster负载",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "hadoop_hbase_averageload{instance=~\"$HMaster\"}",
     "legendFormat": "负载"
    }
   ]
  },
  {
   "title": "Hbase LogFile大小",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "sum(hadoop_hbase_hlogfilesize{instance=~\"$HRegionServer\"})",
     "legendFormat": " LogFile大小"
    }
   ]
  }
 ]
}