{
 "title": "HiveServer2",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(process_start_time_seconds{job='hiveserver2'},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "HiveServer2启动时间",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{job=\"hiveserver2\",instance=\"$instance\"}*1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "运行时长",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=\"hiveserver2\",instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "堆内存使用率",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{area=\"heap\",job=\"hiveserver2\",instance=\"$instance\"}*100/jvm_memory_bytes_max{area=\"heap\",job=\"hiveserver2\",instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HiveServer2堆内存大小",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(java_lang_Memory_HeapMemoryUsage_max{job=\"hiveserver2\",instance=\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "状态",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"hiveserver2\",instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "HiveServer2堆内存使用趋势",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 5 },
   "repeat": "memarea",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{area=\"heap\",job=\"hiveserver2\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "jvm_memory_bytes_max{area=\"heap\",job=\"hiveserver2\",instance=\"$hiveserver2\",instance=~\"$instance\"}",
     "legendFormat": "最大堆内存"
    }
   ]
  },
  {
   "title": "HiveServer2 GC时间趋势图",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "increase(jvm_gc_collection_seconds_sum{job=\"hiveserver2\",instance=~\"$instance\"}[$__interval])",
     "legendFormat": "{{instance}} {{gc}}"
    }
   ]
  }
 ]
}