{
 "title": "hive",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "hivemetastore",
    "label": "hivemetastore",
    "query": {
     "query": "label_values(process_start_time_seconds{job='hivemetastore'},instance)"
    }
   },
   {
    "name": "hiveserver2",
    "label": "hiveserver2",
    "query": {
     "query": "label_values(process_start_time_seconds{job='hiveserver2'},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "hiveserver2启动时间",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{job=\"hiveserver2\",instance =~\"$hiveserver2\"}*1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "hiveserver2在线数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{job=\"hiveserver2\",instance=~\"$hiveserver2\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "hiveserver2离线数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(up{job = \"hiveserver2\" ,instance=~\"$hiveserver2\"}== 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "hivemetastore启动时间",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{job=\"hivemetastore\",instance =~\"$hivemetastore\"}*1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "hivemetastore在线数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{job=\"hivemetastore\",instance=~\"$hivemetastore\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "hivemetastore离线数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(up{job = \"hivemetastore\" ,instance=~\"$hivemetastore\"}== 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "hiveserver2堆内存使用趋势",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{area=\"heap\",job=\"hiveserver2\",instance=~ \"$hiveserver2\"}",
     "legendFormat": "{{instance}}已用堆内存"
    },
    {
     "expr": " jvm_memory_bytes_max{area=\"heap\",job=\"hiveserver2\",instance=~ \"$hiveserver2\"}",
     "legendFormat": " {{instance}}最大堆内存"
    }
   ]
  },
  {
   "title": "hiveserver2 GC时间趋势图",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "increase(jvm_gc_collection_seconds_sum{job=\"hiveserver2\",instance=~ \"$hiveserver2\"}[$__interval])",
     "legendFormat": "{{instance}}{{gc}}"
    }
   ]
  },
  {
   "title": "hivemetastore堆内存使用趋势",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{area=\"heap\",job=\"hivemetastore\",instance=~ \"$hivemetastore\"}",
     "legendFormat": "{{instance}}已用堆内存"
    },
    {
     "expr": " jvm_memory_bytes_max{area=\"heap\",job=\"hivemetastore\",instance=~ \"$hivemetastore\"}",
     "legendFormat": " {{instance}}最大堆内存"
    }
   ]
  },
  {
   "title": "hivemetastore GC时间趋势图",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "increase(jvm_gc_collection_seconds_sum{job=\"hivemetastore\",instance=~ \"$hivemetastore\"}[$__interval])",
     "legendFormat": "{{instance}}{{gc}}"
    }
   ]
  }
 ]
}