{
 "title": "HMaster",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "HMaster",
    "label": "HMaster",
    "query": {
     "query": "label_values(process_start_time_seconds{job=\"HMaster\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "HMaster启动时间",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{job=\"HMaster\",instance=\"$HMaster\"}*1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HMaster运行时间",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=\"HMaster\",instance=\"$HMaster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HMaster堆内存大小",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hadoop_hbase_memheapmaxm{job=\"HMaster\",instance=\"$HMaster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "状态",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"HMaster\",instance=\"$HMaster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "已执行的Assign次数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hadoop_hbase_assigntime_num_ops{instance=\"$HMaster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HMaster堆内存使用率",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(hadoop_hbase_memheapusedm{job=\"HMaster\",instance=\"$HMaster\"}/hadoop_hbase_memheapmaxm{job=\"HMaster\",instance=\"$HMaster\"})*100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "目前正在进行的RIT操作的数量",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hadoop_hbase_ritcount{instance=\"$HMaster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HLog拆分操作的次数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hadoop_hbase_hlogsplitsize_num_ops{instance=\"$HMaster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "元数据HLog拆分操作的次数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hadoop_hbase_metahlogsplitsize_num_ops{instance=\"$HMaster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Assign失败次数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hadoop_hbase_assignfailedcount{instance=\"$HMaster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "图表", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "堆内存使用趋势",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{area=\"heap\",job=\"HMaster\",instance=~ \"$HMaster\"}",
     "legendFormat": "已用堆内存"
    },
    {
     "expr": " jvm_memory_bytes_max{area=\"heap\",job=\"HMaster\",instance=~ \"$HMaster\"}",
     "legendFormat": "最大堆内存"
    }
   ]
  },
  {
   "title": "GC时间趋势图",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "increase(jvm_gc_collection_seconds_sum{job=\"HMaster\",instance=~ \"$HMaster\"}[$__interval])",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  {
   "title": "Region分裂次数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "hadoop_hbase_splittime_num_ops{job=\"HMaster\", instance=\"$HMaster\" }",
     "legendFormat": "分裂次数"
    }
   ]
  },
  {
   "title": "已执行的Balancer操作数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "hadoop_hbase_balancercluster_num_ops{instance=\"$HMaster\"}",
     "legendFormat": "已执行的Balancer操作数"
    }
   ]
  }
 ]
}