{
 "title": "HRegionServer",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "HRegionServer",
    "label": "HRegionServer",
    "query": {
     "query": "label_values(process_start_time_seconds{job=\"HRegionServer\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "HRegionServer启动时间",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{job=\"HRegionServer\",instance=\"$HRegionServer\"}*1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HRegionServer运行时间",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=\"HRegionServer\",instance=\"$HRegionServer\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HRegionServer堆内存大小",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hadoop_hbase_memheapmaxm{job=\"HRegionServer\",instance=\"$HRegionServer\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "状态",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"HRegionServer\",instance=\"$HRegionServer\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Store 个数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hadoop_hbase_storecount{instance=\"$HRegionServer\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HRegionServer堆内存使用率",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(hadoop_hbase_memheapusedm{job=\"HRegionServer\",instance=\"$HRegionServer\"}/hadoop_hbase_memheapmaxm{job=\"HRegionServer\",instance=\"$HRegionServer\"})*100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Region 个数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hadoop_hbase_regioncount{instance=\"$HRegionServer\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WAL 文件数量",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hadoop_hbase_hlogfilecount{instance=\"$HRegionServer\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Block Cache 中的 Block 数量",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hadoop_hbase_blockcachecount{instance=\"$HRegionServer\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "缓存块内存占用大小",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hadoop_hbase_blockcachesize{instance=\"$HRegionServer\", sub=\"Server\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "图表", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "堆内存使用趋势",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{area=\"heap\",job=\"HRegionServer\",instance=~ \"$HRegionServer\"}",
     "legendFormat": "已用堆内存"
    },
    {
     "expr": " jvm_memory_bytes_max{area=\"heap\",job=\"HRegionServer\",instance=~ \"$HRegionServer\"}",
     "legendFormat": "最大堆内存"
    }
   ]
  },
  {
   "title": "GC时间趋势图",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "increase(jvm_gc_collection_seconds_sum{job=\"HRegionServer\",instance=~ \"$HRegionServer\"}[$__interval])",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  {
   "title": "HRegionServer LogFile大小",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "hadoop_hbase_hlogfilesize{instance=\"$HRegionServer\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Get 请求时间超过1s的数量",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "hadoop_hbase_slowgetcount{instance=\"$HRegionServer\"}",
     "legendFormat": "Get 请求时间超过1s的数量"
    }
   ]
  }
 ]
}