{
 "title": "Kafka",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(up{job=\"kafkabroker\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Topic总数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_globaltopiccount{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "活跃的Controllers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_activecontrollercount{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "处于未同步状态Partition个数",
   "type": "stat",
   "description": "某个Topic的某个分区的副本没有跟进同步的分区数量",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_underreplicatedpartitions{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "在线Broker",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kafka_server_replicamanager_leadercount{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "在线分区数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_partitioncount{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "离线分区数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_offlinepartitionscount{job=~\"kafkabroker\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "低于Min Isr partition的个数",
   "type": "stat",
   "description": "某个Topic的某个分区的当前ISR数量小于设置的 ISR",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_underminisrpartitioncount{job=\"kafkabroker\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Directory Offline个数",
   "type": "stat",
   "description": "某个Topic的某个分区的当前ISR数量小于设置的 ISR",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kafka_log_logmanager_offlinelogdirectorycount{job=\"kafkabroker\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Offline Replica个数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_offlinereplicacount{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Leader个数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_leadercount{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Request请求处理线程的空闲比",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(kafka_server_kafkarequesthandlerpool_requesthandleravgidlepercent_count{instance=~\"$instance\"})/1000000000000"
    }
   ]
  },
  {
   "title": "网络处理线程的空闲比",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(kafka_network_socketserver_networkprocessoravgidlepercent{instance=~\"$instance\"})"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Broker堆内存使用率",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{area=\"heap\",job=\"kafkabroker\",instance=~\"$instance\"}*100/jvm_memory_bytes_max{area=\"heap\",job=\"kafkabroker\",instance=~\"$instance\"}",
     "legendFormat": "broker"
    }
   ]
  },
  {
   "title": "KafkaBroker堆内存使用趋势",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum without(area)(jvm_memory_bytes_used{area=\"heap\",job=\"kafkabroker\",instance=~\"$instance\"}*100/jvm_memory_bytes_max{area=\"heap\",job=\"kafkabroker\",instance=~\"$instance\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "消息写入消费速率",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(irate(kafka_server_brokertopicmetrics_bytesin_total{job=\"kafkabroker\",instance=~\"$instance\"}[5m]))",
     "legendFormat": "写入速率"
    },
    {
     "expr": "sum(rate(kafka_server_brokertopicmetrics_bytesout_total{job=\"kafkabroker\",instance=~\"$instance\"}[5m]))",
     "legendFormat": "消费速率"
    }
   ]
  },
  {
   "title": "Topic每秒写入消息速率",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sum(irate(kafka_server_brokertopicmetrics_messagesin_total{job=\"kafkabroker\",instance=~\"$instance\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "GC时间",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum without(gc)(rate(jvm_gc_collection_seconds_sum{job=\"kafkabroker\",instance=~\"$instance\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU使用情况",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{job=\"kafkabroker\",instance=~\"$instance\"}[5m])*100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "控制节点和从节点",
   "type": "table",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "kafka_controller_kafkacontroller_activecontrollercount{job=~\"kafkabroker\",instance=~\"$instance\"}-0",
     "legendFormat": "broker"
    }
   ]
  }
 ]
}