{
 "title": "YARN",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "resourcemanager",
    "label": "resourcemanager",
    "query": {
     "query": "label_values(process_start_time_seconds{job='resourcemanager'},instance)"
    }
   },
   {
    "name": "queue",
    "label": "队列",
    "query": {
     "query": "label_values(Hadoop_ResourceManager_AvailableMB{q1!=\"default\"},q1)"
    }
   },
   {
    "name": "nodemanager",
    "label": "nodemanager",
    "query": {
     "query": "label_values(up{job='nodemanager'},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "ResourceManager启动时间",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{job=\"resourcemanager\",instance=~\"$resourcemanager\"}*1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "已用内存",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(Hadoop_NodeManager_AllocatedGB{instance=~\"$nodemanager\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "总虚拟核数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(Hadoop_NodeManager_AvailableVCores{instance=~\"$nodemanager\"}+Hadoop_NodeManager_AllocatedVCores{instance=~\"$nodemanager\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "已用核数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(Hadoop_NodeManager_AllocatedVCores{instance=~\"$nodemanager\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "NodeManager在线数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(Hadoop_ResourceManager_NumActiveNMs{instance=~\"$resourcemanager\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Yarn虚拟内存",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(Hadoop_NodeManager_AllocatedGB{instance=~\"$nodemanager\"}+Hadoop_NodeManager_AvailableGB{instance=~\"$nodemanager\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lost NodeManager数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(Hadoop_ResourceManager_NumLostNMs{instance=~\"$resourcemanager\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "application提交数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(Hadoop_ResourceManager_AppsSubmitted{job=\"resourcemanager\",name=\"QueueMetrics\",q0=\"root\",q1=\"\",user=\"\",instance=~\"$resourcemanager\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "正在运行的application数量",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(Hadoop_ResourceManager_AppsRunning{job=\"resourcemanager\",name=\"QueueMetrics\",q0=\"root\",q1=\"\",user=\"\",instance=~\"$resourcemanager\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Yarn内核使用率",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(Hadoop_NodeManager_AllocatedVCores{instance=~\"$nodemanager\"})/sum(Hadoop_NodeManager_AvailableVCores{instance=~\"$nodemanager\"}+Hadoop_NodeManager_AllocatedVCores{instance=~\"$nodemanager\"})*100"
    }
   ]
  },
  {
   "title": "Yarn内存使用率",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(Hadoop_NodeManager_AllocatedGB{instance=~\"$nodemanager\"})/sum(Hadoop_NodeManager_AllocatedGB{instance=~\"$nodemanager\"}+Hadoop_NodeManager_AvailableGB{instance=~\"$nodemanager\"})*100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "NodeManager离线数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(up{instance=~\"$nodemanager\"} == 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "等待资源的application数量",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(Hadoop_ResourceManager_AppsPending{job=\"resourcemanager\",name=\"QueueMetrics\",q0=\"root\",instance=~\"$resourcemanager\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "等待处理的资源",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(Hadoop_ResourceManager_PendingMB{q0=\"root\",q1=\"\",user=\"\",instance=~\"$resourcemanager\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " 已分配的container数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(Hadoop_NodeManager_AllocatedContainers{instance=~\"$nodemanager\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "运行中的容器",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(Hadoop_NodeManager_ContainersRunning{instance=~\"$nodemanager\"})"
    }
   ]
  },
  {
   "title": "运行完成的容器",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(Hadoop_NodeManager_ContainersCompleted{instance=~\"$nodemanager\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "运行失败的容器",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(Hadoop_NodeManager_ContainersFailed{instance=~\"$nodemanager\"})"
    }
   ]
  },
  {
   "title": "ResourceManager堆内存大小",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(Hadoop_ResourceManager_MemHeapMaxM{instance=~\"$resourcemanager\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "ResourceManager堆内存使用率",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "Hadoop_ResourceManager_MemHeapUsedM{instance=~\"$resourcemanager\"} *100/ Hadoop_ResourceManager_MemHeapMaxM{instance=~\"$resourcemanager\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "ResourceManager Gc时间",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "Hadoop_ResourceManager_GcTimeMillis{instance=~\"$resourcemanager\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Yarn队列内存使用情况",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "sum(Hadoop_ResourceManager_AllocatedMB{q1!=\"\", user=\"\",name=\"QueueMetrics\",instance=~\"$resourcemanager\"}) by (q1)",
     "legendFormat": "{{q1}}已用内存"
    }
   ]
  },
  {
   "title": "Yarn队列核数使用情况",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(Hadoop_ResourceManager_AllocatedVCores{q1!=\"\", user=\"\",name=\"QueueMetrics\",instance=~\"$resourcemanager\"}) by (q1)",
     "legendFormat": "{{q1}}已用核数"
    }
   ]
  },
  {
   "title": "队列中正在运行的App数",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "Hadoop_ResourceManager_AppsRunning{job=\"resourcemanager\",name=\"QueueMetrics\",instance=~\"$resourcemanager\",q0=\"root\",q1!=\"\",user=\"\"}",
     "legendFormat": "{{q1}}"
    }
   ]
  },
  {
   "title": "RPC心跳时间",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "Hadoop_ResourceManager_RpcQueueTimeAvgTime{instance=~\"$resourcemanager\"}",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}