{
 "title": "Yarn NM Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(up{job=\"nodemanager\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "集群信息", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "NM节点",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(Hadoop_NodeManager_AvailableGB{instance=~\"$instance\"}) by (instance)"
    },
    {
     "expr": "sum(Hadoop_NodeManager_AllocatedContainers{instance=~\"$instance\"}) by (instance)"
    },
    {
     "expr": "sum(Hadoop_NodeManager_AllocatedGB{instance=~\"$instance\"}) by (instance)"
    },
    {
     "expr": "sum(Hadoop_NodeManager_AllocatedVCores{instance=~\"$instance\"}) by (instance)"
    }
   ]
  },
  { "title": "JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "GC次数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(Hadoop_NodeManager_GcCount{instance=~\"$instance\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "GC时间",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(Hadoop_NodeManager_GcTimeMillis{instance=~\"$instance\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "堆使用情况",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "Hadoop_NodeManager_MemHeapUsedM{instance=~\"$instance\"}",
     "legendFormat": "{{instance}} used"
    },
    {
     "expr": "Hadoop_NodeManager_MemHeapMaxM{instance=~\"$instance\"}",
     "legendFormat": "{{instance}} max"
    }
   ]
  }
 ]
}