{
 "title": "Yarn RM Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(up{job=\"resourcemanager\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "集群信息", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "RM节点",
   "type": "table",
   "description": "yarn resourcemanager节点",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(Hadoop_ResourceManager_AvailableMB{instance=~\"$instance\"}) by (instance)",
     "legendFormat": "主机"
    },
    {
     "expr": "sum(Hadoop_ResourceManager_AllocatedContainers{q1!=\"\", user=\"\",instance=~\"$instance\"}) by (instance)",
     "legendFormat": "Containers运行中"
    },
    {
     "expr": "sum(Hadoop_ResourceManager_PendingContainers{q1!=\"\", user=\"\",instance=~\"$instance\"}) by (instance)",
     "legendFormat": "Containers等待执行数"
    },
    {
     "expr": "sum(Hadoop_ResourceManager_ReservedContainers{q1!=\"\", user=\"\",instance=~\"$instance\"}) by (instance)",
     "legendFormat": "Containers预定的"
    },
    {
     "expr": "sum(Hadoop_ResourceManager_AllocatedVCores{q1!=\"\", user=\"\",instance=~\"$instance\"}) by (instance)",
     "legendFormat": "运行中的VCores"
    },
    {
     "expr": "sum(Hadoop_ResourceManager_AvailableVCores{q1!=\"\", user=\"\",instance=~\"$instance\"}) by (instance)",
     "legendFormat": "可用的VCores"
    },
    {
     "expr": "sum(Hadoop_ResourceManager_ReservedVCores{q1!=\"\", user=\"\",instance=~\"$instance\"}) by (instance)",
     "legendFormat": "预定的VCores"
    },
    {
     "expr": "sum(Hadoop_ResourceManager_PendingVCores{q1!=\"\", user=\"\",instance=~\"$instance\"}) by (instance)",
     "legendFormat": "等待执行的VCores"
    }
   ]
  },
  { "title": "作业", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "预占内存",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "Hadoop_ResourceManager_ReservedMB{instance=~\"$instance\"}/1024"
    }
   ]
  },
  {
   "title": "预占CPU核数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "Hadoop_ResourceManager_ReservedVCores{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Running",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(Hadoop_ResourceManager_AppsRunning{q1!=\"\", user=\"\",instance=~\"$instance\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "作业等待数",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(Hadoop_ResourceManager_AppsPending{q1!=\"\", user=\"\",instance=~\"$instance\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "失败作业数",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(Hadoop_ResourceManager_AppsFailed{q1!=\"\", user=\"\",instance=~\"$instance\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "GC次数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(Hadoop_ResourceManager_GcCount{instance=~\"$instance\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "GC时间",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(Hadoop_ResourceManager_GcTimeMillis{instance=~\"$instance\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "堆使用情况",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "Hadoop_ResourceManager_MemHeapUsedM{instance=~\"$instance\"}",
     "legendFormat": "{{instance}} used"
    },
    {
     "expr": "Hadoop_ResourceManager_MemHeapMaxM{instance=~\"$instance\"}",
     "legendFormat": "{{instance}} max"
    }
   ]
  }
 ]
}