{
 "title": "Zookeeper",
 "description": "Metrics was extracted from jmx-exporter that reads JMX data from JVM based applications and exposes it via HTTP in a simple text format that Prometheus understand and can scrape. This dashboard was built for Zookeeper 3.5 version deployment in Kubernetes. You can select metrics based on Pod Instance, Namespace, Application name and Cluster. This dashboard gives cross cluster zookeeper nodes information. It provides Quorum Size, Number of Followers, Member Type information, Healthcheck, Zookeeper metrics and JVM metics. ",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(up {job='zkserver'}, instance)"
    }
   },
   {
    "name": "env",
    "label": "surroundings",
    "query": {
     "query": "label_values(process_start_time_seconds,env)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "ZK启动时间",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{job=\"zkserver\",instance=~\"$instance\"}*1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "总Znodes数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(zookeeper_InMemoryDataTree_NodeCount{instance=~\"$instance\"})",
     "target": "aliasByNode(zookeeper.cluster.$cluster.zookeeper.$zookeeper_hosts.zookeeper.OutstandingRequests, 4, 6)"
    }
   ]
  },
  {
   "title": "角色分配",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "WOW": [
      {
       "checked": false,
       "label": "-1W",
       "offset": 604800000
      },
      {
       "checked": false,
       "label": "-2W",
       "offset": 1209600000
      },
      {
       "checked": false,
       "label": "-3W",
       "offset": 1814400000
      }
     ],
     "aggregator": "COUNT",
     "dataType": "METRICS",
     "expr": "zookeeper_AvgRequestLatency{job=\"zkserver\",instance=~\"$instance\"}",
     "funcByType": "dimension",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "ZK运行时长",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=\"zkserver\",instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ZK堆内存大小",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(jvm_memory_bytes_max{job=\"zkserver\",area=\"heap\",instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "在线节点数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "WOW": [
      {
       "checked": false,
       "label": "-1W",
       "offset": 604800000
      },
      {
       "checked": false,
       "label": "-2W",
       "offset": 1209600000
      },
      {
       "checked": false,
       "label": "-3W",
       "offset": 1814400000
      }
     ],
     "aggregator": "COUNT",
     "dataType": "METRICS",
     "expr": "sum(up{job = \"zkserver\",instance=~\"$instance\"})",
     "funcByType": "dimension"
    }
   ]
  },
  {
   "title": "离线节点数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "WOW": [
      {
       "checked": false,
       "label": "-1W",
       "offset": 604800000
      },
      {
       "checked": false,
       "label": "-2W",
       "offset": 1209600000
      },
      {
       "checked": false,
       "label": "-3W",
       "offset": 1814400000
      }
     ],
     "aggregator": "COUNT",
     "dataType": "METRICS",
     "expr": "count(up{job = \"zkserver\" ,instance=~\"$instance\"}== 0)",
     "funcByType": "dimension"
    }
   ]
  },
  {
   "title": "ZK堆内存使用率",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(jvm_memory_bytes_used{job=\"zkserver\",area=\"heap\",instance=~\"$instance\"}/jvm_memory_bytes_max{job=\"zkserver\",area=\"heap\",instance=~\"$instance\"})*100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "ZK堆内存使用",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{job=\"zkserver\",area=\"heap\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}节点内存使用",
     "target": "aliasByNode(zookeeper.cluster.$cluster.jvm_memory.$zookeeper_hosts.memory.HeapMemoryUsage_used.upper, 4, 6)"
    }
   ]
  },
  {
   "title": "zookeeper watch数",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "expr": "zookeeper_InMemoryDataTree_WatchCount{instance=~\"$instance\"}",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "ZK年轻代GC时间",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "increase(jvm_gc_collection_seconds_sum{job=\"zkserver\",gc=\"PS Scavenge\",instance=~\"$instance\"}[5m])",
     "legendFormat": "{{instance}}年轻代Gc时间",
     "target": "aliasByNode(nonNegativeDerivative(zookeeper.cluster.$cluster.jvm_memory.$zookeeper_hosts.sun_management_GarbageCollectorImpl.PSScavenge.CollectionTime.upper), 4)"
    }
   ]
  },
  {
   "title": "ZK老年代GC时间",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "increase(jvm_gc_collection_seconds_sum{job=\"zkserver\",gc=\"PS MarkSweep\",instance=~\"$instance\"}[5m])",
     "legendFormat": "{{instance}}老年代Gc时间",
     "target": "aliasByNode(nonNegativeDerivative(zookeeper.cluster.$cluster.jvm_memory.$zookeeper_hosts.sun_management_GarbageCollectorImpl.PSScavenge.CollectionTime.upper), 4)"
    }
   ]
  },
  {
   "title": "zk连接依赖数",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 17 },
   "targets": [
    {
     "expr": "zookeeper_NumAliveConnections{instance=~\"$instance\"}",
     "target": "aliasByNode(zookeeper.cluster.$cluster.zookeeper.$zookeeper_hosts.zookeeper.NumAliveConnections, 4, 6)"
    }
   ]
  }
 ]
}