groups:
- name: SPARK
  rules:
  - alert: SparkHistoryServer进程意外终止
    expr: up{job="sparkhistoryserver"}!=1
    for: 3m
    labels:
      level: down
      service: SPARK
      ruleId: 569
    annotations:
      summary: 查看日志，分析宕机原因，解决问题后重新启动
