groups:
- name: HIVE
  rules:
  - alert: HiveServer2进程意外终止
    expr: up{job="hiveserver2"}!=1
    for: 3m
    labels:
      level: down
      service: HIVE
      ruleId: 541
    annotations:
      summary: 查看日志，分析宕机原因，解决问题后重新启动
  - alert: HiveServer2堆内存使用率
    expr: java_lang_Memory_HeapMemoryUsage_used{job="hiveserver2"}*100/java_lang_Memory_HeapMemoryUsage_max{job="hiveserver2"}>95
    for: 3m
    labels:
      level: unhealthy
      service: HIVE
      ruleId: 542
    annotations:
      summary: HiveServer2堆内存不足，增大NameNode堆内存
  - alert: HiveMetastore进程意外终止
    expr: up{job="hivemetastore"}!=1
    for: 3m
    labels:
      level: down
      service: HIVE
      ruleId: 545
    annotations:
      summary: 查看日志，分析宕机原因，解决问题后重新启动
  - alert: HiveMetastore堆内存使用率
    expr: java_lang_Memory_HeapMemoryUsage_used{job="hivemetastore"}*100/java_lang_Memory_HeapMemoryUsage_max{job="hivemetastore"}>95
    for: 3m
    labels:
      level: unhealthy
      service: HIVE
      ruleId: 546
    annotations:
      summary: 请联系管理员
