groups:
- name: KAFKA
  rules:
  - alert: KafkaBorker进程意外终止
    expr: up{job="kafkabroker"}!=1
    for: 3m
    labels:
      level: down
      service: KAFKA
      ruleId: 611
    annotations:
      summary: 查看日志，分析宕机原因，解决问题后重新启动
