groups:
- name: RANGER
  rules:
  - alert: RangerServer进程意外终止
    expr: up{job="rangeradmin"}!=1
    for: 3m
    labels:
      level: down
      service: RANGER
      ruleId: 568
    annotations:
      summary: 查看日志，分析宕机原因，解决问题后重新启动
  - alert: RangerUser进程意外终止
    expr: up{job="rangeruser"}!=1
    for: 3m
    labels:
      level: down
      service: RANGER
      ruleId: 630
    annotations:
      summary: 查看日志，分析宕机原因，解决问题后重新启动
