groups:
- name: FLINK
  rules:
  - alert: FLINKHISTORY进程意外终止
    expr: up{job="flinkhistoryserver"}!=1
    for: 3m
    labels:
      level: down
      service: FLINK
      ruleId: 635
    annotations:
      summary: 查看日志，分析宕机原因，解决问题后重新启动
