services:
  redis-cluster:
    image: redis:6.0.8
    command: redis-cli -a ${REDIS_PWD}  --cluster create  ${HOST_IP}:6380 ${HOST_IP}:6381 ${HOST_IP}:6382 --cluster-replicas 2  --cluster-yes
    depends_on:
      - redis-6380
      - redis-6381
      - redis-6382
    # 创建 Redis 集群的命令，依赖于三个 Redis 实例的启动

  redis-6380:
    image: redis:6.0.8
    container_name: redis-6380
    restart: always
    ports:
      - 6380:6380  # 映射 Redis 端口
      - 16380:16380  # 映射 Redis 的 cluster bus 端口
    volumes:
      - ./etc_rc.local:/etc/rc.local  # 挂载启动脚本
      - ./6380/conf/redis.conf:/etc/redis/redis.conf  # 挂载配置文件
      - ./6380/data:/data  # 挂载数据目录
    command: redis-server /etc/redis/redis.conf  # 启动 Redis 服务的命令

  redis-6381:
    image: redis:6.0.8
    container_name: redis-6381
    restart: always
    ports:
      - 6381:6381
      - 16381:16381
    volumes:
      - ./etc_rc.local:/etc/rc.local
      - ./6381/conf/redis.conf:/etc/redis/redis.conf
      - ./6381/data:/data
    command: redis-server /etc/redis/redis.conf

  redis-6382:
    image: redis:6.0.8
    container_name: redis-6382
    restart: always
    ports:
      - 6382:6382
      - 16382:16382
    volumes:
      - ./etc_rc.local:/etc/rc.local
      - ./6382/conf/redis.conf:/etc/redis/redis.conf
      - ./6382/data:/data
    command: redis-server /etc/redis/redis.conf

  redis-sentinel-26379:
    image: redis:6.0.8
    container_name: redis-sentinel-26379
    ports:
      - 26379:26379
    command: redis-sentinel /etc/redis/sentinel.conf --sentinel
    volumes:
      - ./26379/conf/sentinel.conf:/etc/redis/sentinel.conf  # 挂载 Sentinel 配置文件
    depends_on:
      - redis-6380
      - redis-6381
      - redis-6382
    environment:
      - "SENTINEL_DOWN_AFTER=5000"  # 定义 Sentinel 参数
      - "SENTINEL_FAILOVER=30000"
      - "SENTINEL_PARALLEL_SYNCS=1"

  redis-sentinel-26380:
    image: redis:6.0.8
    container_name: redis-sentinel-26380
    ports:
      - 26380:26380
    command: redis-sentinel /etc/redis/sentinel.conf --sentinel
    volumes:
      - ./26380/conf/sentinel.conf:/etc/redis/sentinel.conf
    depends_on:
      - redis-6380
      - redis-6381
      - redis-6382
    environment:
      - "SENTINEL_DOWN_AFTER=5000"
      - "SENTINEL_FAILOVER=30000"
      - "SENTINEL_PARALLEL_SYNCS=1"

  redis-sentinel-26381:
    image: redis:6.0.8
    container_name: redis-sentinel-26381
    ports:
      - 26381:26381
    command: redis-sentinel /etc/redis/sentinel.conf --sentinel
    volumes:
      - ./26381/conf/sentinel.conf:/etc/redis/sentinel.conf
    depends_on:
      - redis-6380
      - redis-6381
      - redis-6382
    environment:
      - "SENTINEL_DOWN_AFTER=5000"
      - "SENTINEL_FAILOVER=30000"
      - "SENTINEL_PARALLEL_SYNCS=1"