# 使用 Python 官方镜像作为基础镜像
FROM python:3.9-slim

# 设置工作目录
WORKDIR /app

# 复制应用程序代码到容器中
COPY . .

# 设置 pip 加速源为阿里云
RUN pip config set global.index-url https://mirrors.aliyun.com/pypi/simple/

ENV PROMETHEUS_URL=''

# 安装依赖
RUN pip install --no-cache-dir flask requests loguru -i https://mirrors.aliyun.com/pypi/simple/

# 暴露应用程序端口
EXPOSE 5000

# 启动应用程序
CMD ["python", "app.py"]